name: CI/CD backend pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Compile, build, install dependencies and test project
    steps:
      - name: Checkout code from repo that triggered workflow
        uses: actions/checkout@v4

      - name: Setup JDK version and distributor
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # creates unique cache key based on the hash of the pom.xml
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with maven
        run: mvn clean install --batch-mode # responsible for installing, compiling and running tests, all-in-one command
        working-directory: backend


        
